[lite]
browser = false
speech_default = false
mnemopi = false
yt_dlp = false
trafilatura = false
local_models = "none"
max_sfx_bytes = 1990000000

[portable]
browser = true
speech_default = false
mnemopi = false
yt_dlp = false
trafilatura = true
local_models = "none"
max_sfx_bytes = 1990000000
